detailing args for job_submit function

diff --git a/bin/vnc2hpc b/bin/vnc2hpc
--- a/bin/vnc2hpc
+++ b/bin/vnc2hpc
@@ -81,6 +81,174 @@ connect_job () {
 }
 
 #######################################
+# Submit Batch Job
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+slurm_job_submit() {
+    while getopts "A:Q:R:T:C:P:N:" opt; do
+        case $opt in
+            A)  local loc_account="-A ${OPTARG}"		;;
+            Q)  local loc_qos="--qos=${OPTARG}"			;;
+            R)  local loc_reservation="--reservation=${OPTARG}"	;;
+            T)  local loc_walltime="-t ${OPTARG}"		;;
+            C)  local loc_contstraint="-c ${OPTARG}"		;;
+            P)  local loc_partition="-p ${OPTARG}"		;;
+            N)  local loc_numnodes="-n ${OPTARG}"		;;
+            *)  echo "UNKNOWN OPTION"				;;
+        esac
+    done
+    job_submit_cmd="salloc --x11=none --no-shell ${loc_numnodes} ${loc_partition} ${loc_constraint} ${loc_walltime} ${loc_reservation} ${loc_qos} ${loc_account}"
+    inform "Submitting interactive job:" "$(echo ${job_submit_cmd})"
+    JOBID=$( ${job_submit_cmd} )
+    if echo ${JOBID} |grep -qi error ; then
+        die "Salloc failed: ${JOBID}"
+    else
+        JOBID=$( echo $JOBID | grep -i "salloc: Granted job allocation" | awk '{print $5}')
+        while ! job_running ${JOBID} ; do
+           sleep 2
+        done
+    fi
+}
+
+#######################################
+# Cancel JOBID
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+job_cancel() {
+  scancel $1 &>/dev/null
+}
+
+#######################################
+# Check JOBID for Failure
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+job_id_fail() {
+  squeue -j $1 |grep -q 'slurm_load_jobs error: Invalid job id specified' &>/dev/null
+  return $?
+}
+
+#######################################
+# Check JOBID for COMPLETE
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+job_completed() {
+  sacct -j $1 | grep -q COMPLETED
+}
+
+#######################################
+# Check JOBID for CANCEL
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+job_cancelled() {
+  sacct -j $1 | grep "$1 " | grep -q CANCELLED
+}
+
+#######################################
+# Check JOBID for RUNNING
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+job_running() {
+  squeue -j $1 -o %T | grep RUNNING &> /dev/null
+}
+
+#######################################
+# Check JOBID for FAIL
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+job_failed() {
+  #sacct -j $1 | grep FAILED &> /dev/null
+  sacct -j $1 | grep "$1 " | grep FAILED &> /dev/null
+}
+
+#######################################
+# Get maxppn for JOBID
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+maxppn() {
+  MAX_PPN=$(sinfo -h -o '%c'|sed s'/+//g')
+  if [[ -z $MAX_PPN ]] ; then
+    MAX_PPN=1
+  fi
+  echo $MAX_PPN
+}
+
+#######################################
+# Get HEADNODE for JOBID
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+headnode() {
+  SLURM_NODELIST=`squeue -j $1 -o %N | awk '$0 !~ /^NODELIST/'`
+  HEADNODE=`scontrol show hostnames "$SLURM_NODELIST" | head -n 1`
+  echo $HEADNODE
+}
+
+#######################################
+# Tunnel to Jobid
+# Globals:
+#   JOBID
+# Arguments:
+#   None
+# Outputs:
+# ?????
+#######################################
+tunneler() {
+  sleep 10
+  SLURM_NODELIST=`squeue -j $1 -o %N | awk '$0 !~ /^NODELIST/'`
+  reporter "\$SLURM_NODELIST=$SLURM_NODELIST"
+  R0HOST=`scontrol show hostnames "$SLURM_NODELIST" | head -n 1`
+  reporter "Establishing SSH port tunnel to rank 0 node $R0HOST"
+  # Sometimes outputs a TCP_NODE OVERLAY ERROR. Don't know why or how to fix, but it still sets up the tunnel
+  ssh -T -NnR ${PV_SERVER_PORT}:localhost:${PV_SERVER_PORT} $R0HOST >>${DEBUGOUT} 2>>${DEBUGOUTERR} &
+  TUN_PID=$!
+  return $TUN_PID
+}
+
+#######################################
 # Ensure $MACHINE resolves
 # Globals:
 #   MACHINE
